import os
import logging
import base64
import tiktoken
import uuid
from langchain_openai import ChatOpenAI
from langgraph.checkpoint.memory import MemorySaver
from orc.agent import create_agent
from shared.cosmos_db import (
    get_conversation_data
)

# logging level
logging.getLogger("azure").setLevel(logging.WARNING)
logging.getLogger("azure.cosmos").setLevel(logging.WARNING)
LOGLEVEL = os.environ.get("LOGLEVEL", "DEBUG").upper()
logging.basicConfig(level=LOGLEVEL)

async def run(conversation_id, ask, url, client_principal):
    # conversation_id="804f987c-0210-447a-9f63-c215f1b5543b" # hardcoded for testing

    if conversation_id is None or conversation_id == "":
        conversation_id = str(uuid.uuid4())
        logging.info(
            f"[orchestrator] {conversation_id} conversation_id is Empty, creating new conversation_id."
        )

    model = ChatOpenAI(model_name="gpt-4o", temperature=0.3)
    mini_model = ChatOpenAI(model="gpt-4o-mini", temperature=0)

    # conversation_data = get_conversation_data(conversation_id)
    # memory_data_string = conversation_data["memory_data"]

    # memory
    memory = MemorySaver()
    # decoded_data = base64.b64decode("W3siY29uZmlndXJhYmxlIjogeyJ0aHJlYWRfaWQiOiAiODA0Zjk4N2MtMDIxMC00NDdhLTlmNjMtYzIxNWYxYjU1NDNiIiwgInRocmVhZF90cyI6ICIxZWY3NDc5Zi0zZDBhLTZkMmQtODAwNC0yMTk5Y2NmZDYzMTQifX0sIHsidiI6IDEsICJ0cyI6ICIyMDI0LTA5LTE2VDIyOjIxOjAwLjIxNzg4NiswMDowMCIsICJpZCI6ICIxZWY3NDc5Zi0zZDBhLTZkMmQtODAwNC0yMTk5Y2NmZDYzMTQiLCAiY2hhbm5lbF92YWx1ZXMiOiB7InF1ZXN0aW9uIjogIldobyBpcyB0aGUgQ0VPIG9mIEhvbWUgRGVwb3Q/IiwgImdlbmVyYXRpb24iOiAiVGhlIENFTyBvZiBIb21lIERlcG90IGlzIFRlZCBEZWNrZXIuIEhlIGhhcyBzZXJ2ZWQgYXMgdGhlIFByZXNpZGVudCBhbmQgQ0VPIHNpbmNlIE1hcmNoIDIwMjIgYW5kIGhhcyBiZWVuIHRoZSBDaGFpciBzaW5jZSBPY3RvYmVyIDIwMjIgW1sxXV0oaHR0cHM6Ly9zdHJhZzB2bTJiMmh0dnV1Y2xtLmJsb2IuY29yZS53aW5kb3dzLm5ldC9kb2N1bWVudHMvUmV0YWlsZXJzLzIwMjQtaGQtUHJveHklMjBTdGF0ZW1lbnQlMjBGaW5hbC5wZGY/c3Y9MjAyMi0xMS0wMiZzcz1iZnF0JnNydD1zY28mc3A9cndkbGFjdXBpeXRmeCZzZT0yMDI0LTA5LTE3VDIzOjU0OjI3WiZzdD0yMDI0LTA5LTAzVDE1OjU0OjI3WiZzcHI9aHR0cHMmc2lnPTJUR08xUSUyRkZ0alUwVUYyOVdkemU5SVNrJTJCQk5QaTZWYWdST0FMNHZmZiUyQnMlM0QpLiIsICJ3ZWJfc2VhcmNoIjogIk5vIiwgImRvY3VtZW50cyI6IFt7ImxjIjogMSwgInR5cGUiOiAiY29uc3RydWN0b3IiLCAiaWQiOiBbImxhbmdjaGFpbiIsICJzY2hlbWEiLCAiZG9jdW1lbnQiLCAiRG9jdW1lbnQiXSwgImt3YXJncyI6IHsibWV0YWRhdGEiOiB7InNvdXJjZSI6ICJodHRwczovL3N0cmFnMHZtMmIyaHR2dXVjbG0uYmxvYi5jb3JlLndpbmRvd3MubmV0L2RvY3VtZW50cy9SZXRhaWxlcnMvaGQtMXEyMy10cmFuc2NyaXB0LnBkZj9zdj0yMDIyLTExLTAyJnNzPWJmcXQmc3J0PXNjbyZzcD1yd2RsYWN1cGl5dGZ4JnNlPTIwMjQtMDktMTdUMjM6NTQ6MjdaJnN0PTIwMjQtMDktMDNUMTU6NTQ6MjdaJnNwcj1odHRwcyZzaWc9MlRHTzFRJTJGRnRqVTBVRjI5V2R6ZTlJU2slMkJCTlBpNlZhZ1JPQUw0dmZmJTJCcyUzRCIsICJzY29yZSI6IDMuNzI3MzI4NTM4ODk0NjUzM30sICJwYWdlX2NvbnRlbnQiOiAiSEQg4oCTIFEx4oCZMjMgSG9tZSBEZXBvdCBFYXJuaW5ncyBDYWxsIFxuRVZFTlQgREFURS9USU1FOiBNYXkgMTYsIDIwMjMgLyAwOTowMEFNIEVUIFxuIFxuIFxuIFxuIFxuUFJFU0VOVEFUSU9OIFxuIFxuT3BlcmF0b3IgIFxuIFxuR3JlZXRpbmdzLCBhbmQgd2VsY29tZSB0byBUaGUgSG9tZSBEZXBvdCBGaXJzdCBRdWFydGVyIDIwMjMgRWFybmluZ3MgQ29uZmVyZW5jZSBDYWxsLiBBdCB0aGlzIHRpbWUsIGFsbCBcbnBhcnRpY2lwYW50cyBhcmUgaW4gYSBsaXN0ZW4tb25seSBtb2RlLiBBIGJyaWVmIHF1ZXN0aW9uLWFuZC1hbnN3ZXIgc2Vzc2lvbiB3aWxsIGZvbGxvdyB0aGUgZm9ybWFsIFxucHJlc2VudGF0aW9uLiBbT3BlcmF0b3IgSW5zdHJ1Y3Rpb25zXSBBcyBhIHJlbWluZGVyLCB0aGlzIGNvbmZlcmVuY2UgaXMgYmVpbmcgcmVjb3JkZWQuIFxuIFxuSXQgaXMgbm93IG15IHBsZWFzdXJlIHRvIGludHJvZHVjZSB5b3VyIGhvc3QsIElzYWJlbCBKYW5jaS4gUGxlYXNlIGdvIGFoZWFkLiBcbiBcbklzYWJlbCBKYW5jaSAtIFRoZSBIb21lIERlcG90LCBJbmMuIC0gVlAsIElSICYgVHJlYXN1cmVyIFxuIFxuVGhhbmsgeW91LCBDaHJpc3RpbmUsIGFuZCBnb29kIG1vcm5pbmcsIGV2ZXJ5b25lLiBXZWxjb21lIHRvIEhvbWUgRGVwb3QncyBGaXJzdCBRdWFydGVyIDIwMjMgRWFybmluZ3MgXG5DYWxsLiBKb2luaW5nIHVzIG9uIG91ciBjYWxsIHRvZGF5IGFyZSBUZWQgRGVja2VyLCBDaGFpciwgUHJlc2lkZW50IGFuZCBDRU87IEJpbGx5IEJhc3RlaywgRXhlY3V0aXZlIFZpY2UgXG5QcmVzaWRlbnQgb2YgTWVyY2hhbmRpc2luZzsgQW5uLU1hcmllIENhbXBiZWxsLCBFeGVjdXRpdmUgVmljZSBQcmVzaWRlbnQgb2YgVVMgU3RvcmVzIGFuZCBJbnRlcm5hdGlvbmFsIFxuT3BlcmF0aW9uczsgYW5kIFJpY2hhcmQgTWNQaGFpbCwgRXhlY3V0aXZlIFZpY2UgUHJlc2lkZW50IGFuZCBDaGllZiBGaW5hbmNpYWwgT2ZmaWNlci4iLCAidHlwZSI6ICJEb2N1bWVudCJ9fSwgeyJsYyI6IDEsICJ0eXBlIjogImNvbnN0cnVjdG9yIiwgImlkIjogWyJsYW5nY2hhaW4iLCAic2NoZW1hIiwgImRvY3VtZW50IiwgIkRvY3VtZW50Il0sICJrd2FyZ3MiOiB7Im1ldGFkYXRhIjogeyJzb3VyY2UiOiAiaHR0cHM6Ly9zdHJhZzB2bTJiMmh0dnV1Y2xtLmJsb2IuY29yZS53aW5kb3dzLm5ldC9kb2N1bWVudHMvUmV0YWlsZXJzL2hkLTJxMjMtdHJhbnNjcmlwdC5wZGY/c3Y9MjAyMi0xMS0wMiZzcz1iZnF0JnNydD1zY28mc3A9cndkbGFjdXBpeXRmeCZzZT0yMDI0LTA5LTE3VDIzOjU0OjI3WiZzdD0yMDI0LTA5LTAzVDE1OjU0OjI3WiZzcHI9aHR0cHMmc2lnPTJUR08xUSUyRkZ0alUwVUYyOVdkemU5SVNrJTJCQk5QaTZWYWdST0FMNHZmZiUyQnMlM0QiLCAic2NvcmUiOiAzLjcyNTc5NjQ2MTEwNTM0Njd9LCAicGFnZV9jb250ZW50IjogIkhEIOKAkyBRMuKAmTIzIEhvbWUgRGVwb3QgRWFybmluZ3MgQ2FsbCBcbkVWRU5UIERBVEUvVElNRTogQXVndXN0IDE1LCAyMDIzIC8gMDk6MDBBTSBFVCBcbiBcbiBcbiBcblBSRVNFTlRBVElPTiBcbiBcbk9wZXJhdG9yICBcbiBcbkdyZWV0aW5ncywgYW5kIHdlbGNvbWUgdG8gVGhlIEhvbWUgRGVwb3QgU2Vjb25kIFF1YXJ0ZXIgMjAyMyBFYXJuaW5ncyBDb25mZXJlbmNlIENhbGwuIEF0IHRoaXMgdGltZSwgYWxsIFxucGFydGljaXBhbnRzIGFyZSBpbiBhIGxpc3Rlbi1vbmx5IG1vZGUuIEEgYnJpZWYgcXVlc3Rpb24tYW5kLWFuc3dlciBzZXNzaW9uIHdpbGwgZm9sbG93IHRoZSBmb3JtYWwgXG5wcmVzZW50YXRpb24uIFtPcGVyYXRvciBJbnN0cnVjdGlvbnNdIEFzIGEgcmVtaW5kZXIsIHRoaXMgY29uZmVyZW5jZSBpcyBiZWluZyByZWNvcmRlZC4gXG4gXG5JdCBpcyBub3cgbXkgcGxlYXN1cmUgdG8gaW50cm9kdWNlIHlvdXIgaG9zdCwgSXNhYmVsIEphbmNpLiBQbGVhc2UgZ28gYWhlYWQuIFxuIFxuSXNhYmVsIEphbmNpIC0gVGhlIEhvbWUgRGVwb3QsIEluYy4gLSBWUCwgSVIgJiBUcmVhc3VyZXIgXG4gXG5UaGFuayB5b3UsIGFuZCBnb29kIG1vcm5pbmcgZXZlcnlvbmUuICBXZWxjb21lIHRvIEhvbWUgRGVwb3TigJlzIHNlY29uZCBxdWFydGVyICBcbjIwMjMgZWFybmluZ3MgY2FsbC4gICBcbiBcbkpvaW5pbmcgdXMgb24gb3VyIGNhbGwgdG9kYXkgYXJlIFRlZCBEZWNrZXIsIENoYWlyLCBQcmVzaWRlbnQgYW5kIENFTzsgQmlsbHkgQmFzdGVrLCBFeGVjdXRpdmUgVmljZSBcblByZXNpZGVudCBvZiBNZXJjaGFuZGlzaW5nOyBBbm4gTWFyaWUgQ2FtcGJlbGwsIEV4ZWN1dGl2ZSBWaWNlIFByZXNpZGVudCBvZiBVUyBTdG9yZXMgYW5kIEludGVybmF0aW9uYWwgXG5PcGVyYXRpb25zIGFuZCBSaWNoYXJkIE1jUGhhaWwsIEV4ZWN1dGl2ZSBWaWNlIFByZXNpZGVudCBhbmQgQ2hpZWYgRmluYW5jaWFsIE9mZmljZXIuIiwgInR5cGUiOiAiRG9jdW1lbnQifX0sIHsibGMiOiAxLCAidHlwZSI6ICJjb25zdHJ1Y3RvciIsICJpZCI6IFsibGFuZ2NoYWluIiwgInNjaGVtYSIsICJkb2N1bWVudCIsICJEb2N1bWVudCJdLCAia3dhcmdzIjogeyJtZXRhZGF0YSI6IHsic291cmNlIjogImh0dHBzOi8vc3RyYWcwdm0yYjJodHZ1dWNsbS5ibG9iLmNvcmUud2luZG93cy5uZXQvZG9jdW1lbnRzL1JldGFpbGVycy8yMDI0LWhkLVByb3h5JTIwU3RhdGVtZW50JTIwRmluYWwucGRmP3N2PTIwMjItMTEtMDImc3M9YmZxdCZzcnQ9c2NvJnNwPXJ3ZGxhY3VwaXl0Zngmc2U9MjAyNC0wOS0xN1QyMzo1NDoyN1omc3Q9MjAyNC0wOS0wM1QxNTo1NDoyN1omc3ByPWh0dHBzJnNpZz0yVEdPMVElMkZGdGpVMFVGMjlXZHplOUlTayUyQkJOUGk2VmFnUk9BTDR2ZmYlMkJzJTNEIiwgInNjb3JlIjogMy41MjI4MjQ3NjQyNTE3MDl9LCAicGFnZV9jb250ZW50IjogInNpbmNlOiAyMDIyXG5BZ2U6IDYxXG5DaGFpciwgUHJlc2lkZW50IGFuZCBcbkNFT1xuXG5Nci4gRGVja2VyIGhhcyBzZXJ2ZWQgYXMgb3VyIENoYWlyIHNpbmNlIE9jdG9iZXIgMjAyMiBhbmQgYXMgb3VyIFByZXNpZGVudCBhbmQgXG5DRU8gc2luY2UgTWFyY2ggMjAyMi4gUHJpb3IgdG8gYXNzdW1pbmcgdGhlIHJvbGUgb2YgQ0VPLCBoZSBzZXJ2ZWQgYXMgb3VyIFxuUHJlc2lkZW50IGFuZCBDT08gZnJvbSBPY3RvYmVyIDIwMjAgdGhyb3VnaCBGZWJydWFyeSAyMDIyLCB3aGVyZSBoZSB3YXMgXG5yZXNwb25zaWJsZSBmb3IgZ2xvYmFsIHN0b3JlIG9wZXJhdGlvbnMsIGdsb2JhbCBzb3VyY2luZyBvcGVyYXRpb25zLCBnbG9iYWwgc3VwcGx5IFxuY2hhaW4sIG91dHNpZGUgc2FsZXMgYW5kIHNlcnZpY2UsIGFuZCByZWFsIGVzdGF0ZSwgYXMgd2VsbCBhcyBtZXJjaGFuZGlzaW5nLCBcbm1hcmtldGluZyBhbmQgb25saW5lIHN0cmF0ZWd5LiBGcm9tIEF1Z3VzdCAyMDE0IHRvIE9jdG9iZXIgMjAyMCwgaGUgc2VydmVkIGFzIFxuRXhlY3V0aXZlIFZpY2UgUHJlc2lkZW50IOKAkyBNZXJjaGFuZGlzaW5nLCB3aGVyZSBoZSB3YXMgcmVzcG9uc2libGUgZm9yIFxubWVyY2hhbmRpc2luZyBzdHJhdGVneSwgbWFya2V0aW5nLCB2ZW5kb3IgbWFuYWdlbWVudCwgYW5kIGluLXN0b3JlIGVudmlyb25tZW50LiBcbkZyb20gT2N0b2JlciAyMDA2IHRocm91Z2ggSnVseSAyMDE0LCBoZSBzZXJ2ZWQgYXMgU2VuaW9yIFZpY2UgUHJlc2lkZW50IOKAkyBSZXRhaWwgXG5GaW5hbmNlLCBQcmljaW5nIEFuYWx5dGljcywgYW5kIEFzc29ydG1lbnQgUGxhbm5pbmcuIE1yLiBEZWNrZXIgam9pbmVkIFRoZSBIb21lIFxuRGVwb3QgaW4gMjAwMCBhbmQgaGVsZCB2YXJpb3VzIHN0cmF0ZWdpYyBwbGFubmluZyByb2xlcywgaW5jbHVkaW5nIHNlcnZpbmcgYXMgVmljZSBcblByZXNpZGVudCDigJMgU3RyYXRlZ2ljIEJ1c2luZXNzIERldmVsb3BtZW50IGZyb20gTm92ZW1iZXIgMjAwMiB0byBBcHJpbCAyMDA2IiwgInR5cGUiOiAiRG9jdW1lbnQifX1dLCAiZ2VuZXJhdGUiOiAiZ2VuZXJhdGUifSwgImNoYW5uZWxfdmVyc2lvbnMiOiB7Il9fc3RhcnRfXyI6IDEsICJxdWVzdGlvbiI6IDYsICJzdGFydDpyZXRyaWV2YWxfdHJhbnNmb3JtX3F1ZXJ5IjogMiwgInJldHJpZXZhbF90cmFuc2Zvcm1fcXVlcnkiOiAzLCAicmV0cmlldmUiOiA0LCAiZG9jdW1lbnRzIjogNSwgImdyYWRlX2RvY3VtZW50cyI6IDUsICJ3ZWJfc2VhcmNoIjogNSwgImJyYW5jaDpncmFkZV9kb2N1bWVudHM6ZGVjaWRlX3RvX2dlbmVyYXRlOmdlbmVyYXRlIjogNSwgIndlYl9zZWFyY2hfbm9kZSI6IDAsICJnZW5lcmF0ZSI6IDYsICJnZW5lcmF0aW9uIjogNn0sICJ2ZXJzaW9uc19zZWVuIjogeyJfX3N0YXJ0X18iOiB7Il9fc3RhcnRfXyI6IDF9LCAicmV0cmlldmFsX3RyYW5zZm9ybV9xdWVyeSI6IHsic3RhcnQ6cmV0cmlldmFsX3RyYW5zZm9ybV9xdWVyeSI6IDJ9LCAicmV0cmlldmUiOiB7InJldHJpZXZhbF90cmFuc2Zvcm1fcXVlcnkiOiAzfSwgImdyYWRlX2RvY3VtZW50cyI6IHsicmV0cmlldmUiOiA0fSwgImdlbmVyYXRlIjogeyJicmFuY2g6Z3JhZGVfZG9jdW1lbnRzOmRlY2lkZV90b19nZW5lcmF0ZTpnZW5lcmF0ZSI6IDUsICJ3ZWJfc2VhcmNoX25vZGUiOiAwfSwgInRyYW5zZm9ybV9xdWVyeSI6IHt9LCAid2ViX3NlYXJjaF9ub2RlIjoge319LCAicGVuZGluZ19zZW5kcyI6IFtdfSwgeyJzb3VyY2UiOiAibG9vcCIsICJzdGVwIjogNCwgIndyaXRlcyI6IHsiZ2VuZXJhdGUiOiB7InF1ZXN0aW9uIjogIldobyBpcyB0aGUgQ0VPIG9mIEhvbWUgRGVwb3Q/IiwgImdlbmVyYXRpb24iOiAiVGhlIENFTyBvZiBIb21lIERlcG90IGlzIFRlZCBEZWNrZXIuIEhlIGhhcyBzZXJ2ZWQgYXMgdGhlIFByZXNpZGVudCBhbmQgQ0VPIHNpbmNlIE1hcmNoIDIwMjIgYW5kIGhhcyBiZWVuIHRoZSBDaGFpciBzaW5jZSBPY3RvYmVyIDIwMjIgW1sxXV0oaHR0cHM6Ly9zdHJhZzB2bTJiMmh0dnV1Y2xtLmJsb2IuY29yZS53aW5kb3dzLm5ldC9kb2N1bWVudHMvUmV0YWlsZXJzLzIwMjQtaGQtUHJveHklMjBTdGF0ZW1lbnQlMjBGaW5hbC5wZGY/c3Y9MjAyMi0xMS0wMiZzcz1iZnF0JnNydD1zY28mc3A9cndkbGFjdXBpeXRmeCZzZT0yMDI0LTA5LTE3VDIzOjU0OjI3WiZzdD0yMDI0LTA5LTAzVDE1OjU0OjI3WiZzcHI9aHR0cHMmc2lnPTJUR08xUSUyRkZ0alUwVUYyOVdkemU5SVNrJTJCQk5QaTZWYWdST0FMNHZmZiUyQnMlM0QpLiJ9fX0sIG51bGxd")
    # json_data = memory.serde.loads(decoded_data)
    # memory.put(
    #     config=json_data[0], checkpoint=json_data[1], metadata=json_data[2]
    # )

    # create agent
    agent_executor = create_agent(
        model, 
        mini_model, 
        checkpointer=memory,
        verbose=True
    )

    # config
    config = {"configurable": {"thread_id": conversation_id}}

    # print("LOADED MEMOORY:", memory.get_tuple(config))

    # agent response
    response = agent_executor.invoke(
        {"question": ask},
        config,
    )

    # Final generation
    logging.info(
        f"[orchestrator] {conversation_id} agent response: {response['generation'][:50]}"
    )


    # memory serialization
    _tuple = memory.get_tuple(config)
    serialized_data = memory.serde.dumps(_tuple)
    byte_string = base64.b64encode(serialized_data)
    b64_tosave = byte_string.decode("utf-8")

    # print(b64_tosave)
    # print(_tuple)

    return { "response": response["generation"] }
